### PR TITLE
Add Google search console verification

### PR DESCRIPTION
**Pull request by zstadler**

### CODE REVIEW

**Comment by HarelM** [comment]
I don't think this would be helpful here, probably better to place it behind the nginx...

**Comment by zstadler** [comment]
You already added yours
https://github.com/IsraelHikingMap/Site/blob/main/IsraelHiking.Web/src/googlef59316cdb0845a8c.html

**Comment by HarelM** [comment]
I think we should move it out of here.
But if you insist on having it here, please replace the current one and add it to the angular.json file as well:
https://github.com/IsraelHikingMap/Site/blob/009710f6cd5e7cf19e0d45a1f3bf951ce9c6cc29/IsraelHiking.Web/angular.json#LL24C8-L24C8

**Comment by HarelM** [comment]
I don't think this is needed. Closing.

**Pull request closed without merging**
