### PR TITLE
Fix the margin in ltr layout

### PR DESCRIPTION
**Pull request by moshfeu**

### CODE REVIEW

**Comment by HarelM** [comment]
Please resolve conflicts.

**Comment by HarelM** [comment]
FYI, still waiting for conflict resolution in case you were wondering why I'm not merging this to master.

**Comment by HarelM** [comment]
@moshfeu I have merge the changes but the max-width=400px is causing a bug in the sidebar which needs to be fixed, I'll open a bug on it and assign it to you.

**Comment by moshfeu** [comment]
Ok.

**Pull request merged**
