### PR TITLE
GraphHopper JAR update

### PR DESCRIPTION
**Pull request by zstadler**
Updated version of ```car4wd``` profile from graphhopper/master.

Jar updating batch script

### CODE REVIEW

**Comment by HarelM** [comment]
I'm not sure I follow the logic in the following file:
```Graphhopper Java Update.bat``` can you elaborate what it does?

**Comment by zstadler** [comment]
This script updates the JAR files the JAR files in the ```IsraelHikingMap\Site``` repository from the latest JAR files built in the ```IsraelHikingMap\graphhopper``` repository.

It uses ```~dp0``` to determine the location of the target directory

**Comment by zstadler** [comment]
I don't understand how the coverage decreased when the only change was in the comments in a BAT file....

**Comment by HarelM** [comment]
I think you can ignore it. I need to see why it's so low, it used to be above 90.
Probably a check-in I made to the image creator that reflects on the stable branch.
I don't see much use to this script now that I understand what it does (basically automates a few simple delete-copy-paste actions which assumes something about where graphhopper code is), but I'm not sure I care enough to remove it from source control, I'll probably won't use it so it's your call...

**Comment by zstadler** [comment]
I appreciate you keeping the script.

IMHO, the script is very useful, but only when we build the GraphHopper JAR files from the ```IsraelHikingMap\graphhopper``` repository.
It also has a side-benefit of clarifying the dependency between the two repositories.

**Pull request merged**
