### PR TITLE
Added Survey of Israel's Orthophoto (UNTESTED)

### PR DESCRIPTION
**Pull request by nonZero**
Source: <http://data-mapiil.opendata.arcgis.com>

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for the pull request!
But I'm not sure why all the users should have two satellite imagery as default layers.
If needed, a user can add a custom layer such as MAPI 2015.
If you think MAPS 2015 is better than esri than please elaborate your claim and replace esri.

**Comment by HarelM** [comment]
@nonZero as per your question about POIs data that are not wikipedia, the answer is that the POIs' data is comming from [OSM](https://www.openstreetmap.org).

**Comment by HarelM** [comment]
@nonZero Please respond in the next few days, otherwise this pull request will be closed without merging it.

**Comment by nonZero** [comment]
I agree that one satellite basemap is enough.  esri seems to be better. Closing...

**Pull request closed without merging**
