### PR TITLE
Migrate to OAuth2

### LINKED ISSUE #1968: Consider using async pattern for TokenValidation
### What is the problem this feature will solve?

Infrastructure "tech debt"

### What is the feature you are proposing to solve the problem?

Using the new syntax and infrastructure as described here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/468

### What alternatives have you considered or tried?

Keep the code as is.

### Additional information

I'm not sure it's worth the trouble.
Last time I touched this part of the code I caused a deadlock for users trying to login, so this code is risky.
Having said that, it might be the "right way" to write this code, I'm not sure...

### LINKED ISSUE #1985: Sunset Oauth1
### What is the problem this feature will solve?

OAuth 1 in OSM will be deprecated soon (01.06.2024) so there's a need to move the users to OAuth 2.
https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490

### What is the feature you are proposing to solve the problem?

Show a confirmation message allowing to re-login.

### What alternatives have you considered or tried?

Simply logging the users out, but then non technical users might not see the sad icon.

### Additional information

This will happen in a few phases:
1. ~Show the message to users~
2. ~Allow anonymous related actions to pass in the client side~
3. Remove support for OAuth 1 from the server side - this is the last step, only after OSM stops their support.

### PR DESCRIPTION
**Pull request by HarelM**
Since OAuth 1 will be deprecated soon in OSM, remove it from our code and only use OAuth 2.
The code base already handles OAuth2 well, so I removed all the places where OAuth 1 is used.
I also removed the need to authenticate from routes that are not "guarded".
This will affect users who did not clean the app / did a logout-login / installed the app recently (In the last 1.5 years since #1798 was published).

Closes #1968
Resolves #1985 

I have tried to migrate the code to use the following webtokenhandler but the documentation is lacking and I think that it will end up very close to what I did anyway, so this closes this issue without implementing it.

- #1968

FYI: @zstadler

### CODE REVIEW

**Comment by zstadler** [comment]
What is the planned user experience for those who still use OAuth1?
The server shos about 2 such requests per minute

**Comment by HarelM** [comment]
The client will get a 401, current client code doesn't do anything with it, besides showing generic error code according to the relevant operation.
I can change the client code to logout, which is the usual behavior for such a case, but this won't affect clients that are not up to date.

**Comment by HarelM** [comment]
Also the rate will be dramatically reduced, as most operations do not require a logged in user.

**Comment by zstadler** [comment]
How difficult would it be to add user migration code to the client, as you did during the migration to pmtiles?
Any simple mechanism would do, even a "Please logout and login" popup, as long as the reliance on OAuth1 credentials is not silently ignored.

**Comment by HarelM** [comment]
I can check the current token and logout the user in case of oauth1. The current code will force the next login to be of oauth2 type.
This is the easiest solution I believe as I only need to delete the user info from the state.

**Pull request merged**
