### PR TITLE
sidebar header sticky top fix

### PR DESCRIPTION
**Pull request by MAvaisAshraf**
I added a wrapper to the sidebar title and close icon and added CSS to make them sticky at the top when scrolling the sidebar.

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks! Can you share a video of the side bar opening and scrolling?

**Comment by HarelM** [comment]
Don't worry about the CI, it's OK.

**Comment by zstadler** [comment]
[sidebar-video.webm](https://github.com/user-attachments/assets/7a36b554-dfe2-432f-825d-8b7f7b4d5854)

**Comment by HarelM** [comment]
Please use the following for common dialog styling: 
https://github.com/IsraelHikingMap/Site/blob/99248b109e6d737a08f71b44988f36cf0718a6a3/IsraelHiking.Web/src/scss/dialogs.scss

**Review by HarelM — APPROVED** [review]

**Pull request merged**
