### PR TITLE
Osm dialog

### PR DESCRIPTION
**Pull request by moshfeu**
https://github.com/IsraelHikingMap/Site/issues/371

### CODE REVIEW

**Comment by HarelM** [comment]
Please resolve conflicts...

**Comment by HarelM** [comment]
Can you elaborate why you chose to use css and not flex-box framework?
I know that using css will probably solve most issues easily, but I did try and solve most of it with flex-box rather than css to keep the solution consistent throughout the application...

**Comment by HarelM** [comment]
Merged, Still waiting for your response above.
I'm planning on renaming most of the file to follow the angular style guide.
Let me know if you have work that is not checked-in so I'll wait with these changes.
I think it will be wiser to re-fork once I complete the renaming.

**Comment by moshfeu** [comment]
I tried to use flex framework but the main challange is the responsive topic. As much as I understood, I can't set the property flex only for desktop. Once I'm using for one platform it will add the flex for the other too and it was difficult to handle. I will understand if you won't want a code which not consistent to the project..
Keep me update when I could re-fork the project.

**Comment by HarelM** [comment]
It's beautiful, thanks! I agree that the flex framework is very hard to handle, especially the part where you can't just change the css in the browser and see how it looks, I tried very hard to make it work but I tend to agree it's not worth the fighting...
Please note that your conflict resolution removed the pagination I added for the traces :-/
I'll add it back...

**Comment by moshfeu** [comment]
Glad you liked it :) And agree about the framework. In generally I don't like frameworks that use javascript for the styling. I know that it looks like magic but this exactly the problem. Anyway, in the future, I will keep to try to use the framework as much as I could.

Sorry about the pagination.. I'm still learning how to use branches and pull requests with forks on github due I never used it. (Worked on TFS or in github on the master directly)

**Comment by HarelM** [comment]
No worries, Thanks for all your help!

**Comment by HarelM** [comment]
Changing the file names is now my current task, I hope to finish it today-tomorrow and start working on the split-merge route.

**Pull request merged**
